### ISSUE TITLE
unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by ycs77** [Juhlinus/depictr#3]
Hello, I wanted to test whether the rendering result was successful, so I added a Laravel project and installed Depictr, running in my Homestead, and forced to return the rendered page:

*vendor/juhlinus/depictr/src/Middleware.php*
```php
<?php

...

    public function handle($request, Closure $next): Response
    {
        $response = $this->requestRenderedPage($request->fullUrl());

        return response($response['content'], $response['code']);

        // if ($this->shouldDepict($request)) {
        //     try {
        //         $response = $this->requestRenderedPage($request->fullUrl());
        //     } catch (RuntimeException $exception) {
        //         return $next($request);
        //     }

        //     return response(
        //         $response['content'],
        //         $response['code'],
        //     );
        // }

        // return $next($request);
    }
```

But when I browse the Laravel page, I get the following error:

![Error](https://user-images.githubusercontent.com/38133356/80726136-96a34a00-8b36-11ea-9eeb-cf166749e93f.jpg)

How can I solve it?

**Comment by Juhlinus** [comment]
Hello @ycs77 !

Panther that Depictr uses only supports Mac and Linux. Are you running this on Windows by any chance?

**Comment by ycs77** [comment]
@Juhlinus Yes, But I running it, have two error.

OS: Win10
PHP: 7.2
XAMPP: 3.2.4

### Error 1:

`syntax error, unexpected ')'`

![2](https://user-images.githubusercontent.com/38133356/80732896-8a6fba80-8b3f-11ea-8881-9d2c10cb9c7f.jpg)

I deleted the dot and it works in PHP 7.2. But......

### Error 2:

I ran the code in the comment above on Win10, to forced to return the rendered page, now, return error:

`unknown error: cannot create temp dir for user data dir`

![3](https://user-images.githubusercontent.com/38133356/80733501-5a74e700-8b40-11ea-8944-e47891accfed.jpg)

I tried to find a solution, but I haven't found it yet.

**Comment by ycs77** [comment]
Symfony panther is support Windows 🙂

![code 1](https://user-images.githubusercontent.com/38133356/80734057-2c43d700-8b41-11ea-981e-bdffc8900d30.jpg)

**Comment by Juhlinus** [comment]
> ### Error 1:
> `syntax error, unexpected ')'`
> 
> I deleted the dot and it works in PHP 7.2. But......

Yeah this is my bad, this is a new feature in PHP 7.3, I'll add the minimum requirement for php version in composer.

> 
> ### Error 2:
> I ran the code in the comment above on Win10, to forced to return the rendered page, now, return error:
> 
> `unknown error: cannot create temp dir for user data dir`
> 
> I tried to find a solution, but I haven't found it yet.

This seems to be a permission issue, perhaps? I don't think this is related to Depictr itself, and it's probably better to post an issue on the [Webdriver repo](https://github.com/php-webdriver/php-webdriver).

**Comment by ycs77** [comment]
> This seems to be a permission issue, perhaps? I don't think this is related to Depictr itself, and it's probably better to post an issue on the Webdriver repo.

Yes, It no related

**Comment by ycs77** [comment]
Back to the original question, Just after I installed `chromium-browser` in Homestead, I can use it.

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install chromium-browser
chromium-browser -version
```

Install the old version for ChromeDriver, the same version as Chromium (https://chromedriver.storage.googleapis.com/index.html), and add ChromeDriver path to `.env`:
```
PANTHER_CHROME_DRIVER_BINARY=/home/vagrant/code/inertiajs-test/storage/bin/chromedriver-84-linux64
```

**Comment by ycs77** [comment]
@Juhlinus I later thought about it, in fact, we can also ignore Windows, because most PHP websites provide services on Linux.
